name: Build and deploy .NET application to Container App mvc60nogit-app-20220401082311
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: andy41container
  CONTAINER_APP_NAME: mvc60nogit-app-20220401082311
  CONTAINER_APP_RESOURCE_GROUP_NAME: aapt0401LinuxGroup
  CONTAINER_REGISTRY_LOGIN_SERVER: mvc60nogit20220401082702.azurecr.io
  DOCKER_FILE_PATH: Mvc60NoGit/Dockerfile
  PROJECT_NAME_FOR_DOCKER: mvc60nogit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.Mvc60NoGit20220401082702_USERNAME_FFFF }}
        password: ${{ secrets.Mvc60NoGit20220401082702_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.mvc60nogit_app_20220401082311_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"

          az extension add --name containerapp --yes

          echo "Starting Deploying"

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --debug
    - name: logout
      run: >
        az logout
